version: 2
updates:
  # 1. Go Modulesの依存関係を管理
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # Goモジュールの更新を "go-modules" グループのPRにまとめる
    groups:
      go-modules:
        patterns:
          - "*"

  # 2. Dockerイメージの依存関係を管理 (docker-compose.yml, Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    # Dockerイメージの更新を "docker-images" グループのPRにまとめる
    groups:
      docker-images:
        patterns:
          - "*"

  # 3. GitHub Actionsの依存関係を管理
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # GitHub Actionsの更新を "github-actions" グループのPRにまとめる
    groups:
      github-actions:
        patterns:
          - "*"
